from PyQt5 import QtCore, QtGui, QtWidgets
from calculateSmart import CalculateSmart

        
class Ui_Calculate(object):
    ourEval = CalculateSmart()
    def setupUi(self, Calculate):
        Calculate.setObjectName("Calculate")
        Calculate.resize(731, 400)
        Calculate.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Calculate.setMouseTracking(False)
        Calculate.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(Calculate)
        self.centralwidget.setObjectName("centralwidget")
        self.label_result = QtWidgets.QLabel(self.centralwidget)
        self.label_result.setGeometry(QtCore.QRect(490, 10, 221, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_result.setFont(font)
        self.label_result.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_result.setMouseTracking(False)
        self.label_result.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_result.setStyleSheet("background-color: rgb(200,170,170)")
        self.label_result.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_result.setObjectName("label_result")
        self.label_input = QtWidgets.QLabel(self.centralwidget)
        self.label_input.setGeometry(QtCore.QRect(30, 10, 401, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_input.setFont(font)
        self.label_input.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_input.setMouseTracking(False)
        self.label_input.setStyleSheet("background-color: rgb(200,170,170)")
        self.label_input.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_input.setObjectName("label_input")
        self.label_equal = QtWidgets.QLabel(self.centralwidget)
        self.label_equal.setGeometry(QtCore.QRect(430, 10, 61, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_equal.setFont(font)
        self.label_equal.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_equal.setMouseTracking(False)
        self.label_equal.setStyleSheet("background-color: rgb(200,170,170)")
        self.label_equal.setAlignment(QtCore.Qt.AlignCenter)
        self.label_equal.setObjectName("label_equal")
        self.btn_0 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_0.setGeometry(QtCore.QRect(130, 290, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_0.setFont(font)
        self.btn_0.setStyleSheet("color: rgb(30, 70, 30);\n"
"background-color: rgb(250, 170, 220)")
        self.btn_0.setObjectName("btn_0")
        self.btn_8 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_8.setGeometry(QtCore.QRect(130, 240, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_8.setFont(font)
        self.btn_8.setStyleSheet("color: rgb(30, 70, 30);\n"
"background-color: rgb(250, 170, 220)")
        self.btn_8.setObjectName("btn_8")
        self.btn_9 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_9.setGeometry(QtCore.QRect(190, 240, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_9.setFont(font)
        self.btn_9.setStyleSheet("color: rgb(30, 70, 30);\n"
"background-color: rgb(250, 170, 220)")
        self.btn_9.setObjectName("btn_9")
        self.btn_7 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_7.setGeometry(QtCore.QRect(70, 240, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_7.setFont(font)
        self.btn_7.setStyleSheet("color: rgb(30, 70, 30);\n"
"background-color: rgb(250, 170, 220)")
        self.btn_7.setObjectName("btn_7")
        self.btn_4 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_4.setGeometry(QtCore.QRect(70, 190, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_4.setFont(font)
        self.btn_4.setStyleSheet("color: rgb(30, 70, 30);\n"
"background-color: rgb(250, 170, 220)")
        self.btn_4.setObjectName("btn_4")
        self.btn_5 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_5.setGeometry(QtCore.QRect(130, 190, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_5.setFont(font)
        self.btn_5.setStyleSheet("color: rgb(30, 70, 30);\n"
"background-color: rgb(250, 170, 220)")
        self.btn_5.setObjectName("btn_5")
        self.btn_6 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_6.setGeometry(QtCore.QRect(190, 190, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_6.setFont(font)
        self.btn_6.setStyleSheet("color: rgb(30, 70, 30);\n"
"background-color: rgb(250, 170, 220)")
        self.btn_6.setObjectName("btn_6")
        self.btn_1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_1.setGeometry(QtCore.QRect(70, 140, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_1.setFont(font)
        self.btn_1.setStyleSheet("color: rgb(30, 70, 30);\n"
"background-color: rgb(250, 170, 220)")
        self.btn_1.setObjectName("btn_1")
        self.btn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_2.setGeometry(QtCore.QRect(130, 140, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_2.setFont(font)
        self.btn_2.setStyleSheet("color: rgb(30, 70, 30);\n"
"background-color: rgb(250, 170, 220)")
        self.btn_2.setObjectName("btn_2")
        self.btn_3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_3.setGeometry(QtCore.QRect(190, 140, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_3.setFont(font)
        self.btn_3.setStyleSheet("color: rgb(30, 70, 30);\n"
"background-color: rgb(250, 170, 220)")
        self.btn_3.setObjectName("btn_3")
        self.btn_equal = QtWidgets.QPushButton(self.centralwidget)
        self.btn_equal.setGeometry(QtCore.QRect(190, 290, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_equal.setFont(font)
        self.btn_equal.setStyleSheet("color: rgb(30, 70, 30);\n"
"background-color: rgb(250, 170, 220)")
        self.btn_equal.setObjectName("btn_equal")
        self.btn_division = QtWidgets.QPushButton(self.centralwidget)
        self.btn_division.setGeometry(QtCore.QRect(250, 140, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_division.setFont(font)
        self.btn_division.setStyleSheet("color: rgb(30, 70, 30);\n"
"background-color: rgb(250, 170, 220)")
        self.btn_division.setObjectName("btn_division")
        self.btn_remainder_of_division = QtWidgets.QPushButton(self.centralwidget)
        self.btn_remainder_of_division.setGeometry(QtCore.QRect(250, 190, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_remainder_of_division.setFont(font)
        self.btn_remainder_of_division.setStyleSheet("color: rgb(30, 70, 30);\n"
"background-color: rgb(250, 170, 220)")
        self.btn_remainder_of_division.setObjectName("btn_remainder_of_division")
        self.btn_minus = QtWidgets.QPushButton(self.centralwidget)
        self.btn_minus.setGeometry(QtCore.QRect(70, 90, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_minus.setFont(font)
        self.btn_minus.setStyleSheet("color: rgb(30, 70, 30);\n"
"background-color: rgb(250, 170, 220)")
        self.btn_minus.setObjectName("btn_minus")
        self.btn_plus = QtWidgets.QPushButton(self.centralwidget)
        self.btn_plus.setGeometry(QtCore.QRect(130, 90, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_plus.setFont(font)
        self.btn_plus.setStyleSheet("color: rgb(30, 70, 30);\n"
"background-color: rgb(250, 170, 220)")
        self.btn_plus.setObjectName("btn_plus")
        self.btn_multiply = QtWidgets.QPushButton(self.centralwidget)
        self.btn_multiply.setGeometry(QtCore.QRect(190, 90, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_multiply.setFont(font)
        self.btn_multiply.setStyleSheet("color: rgb(30, 70, 30);\n"
"background-color: rgb(250, 170, 220)")
        self.btn_multiply.setObjectName("btn_multiply")
        self.btn_pow = QtWidgets.QPushButton(self.centralwidget)
        self.btn_pow.setGeometry(QtCore.QRect(250, 90, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_pow.setFont(font)
        self.btn_pow.setStyleSheet("color: rgb(30, 70, 30);\n"
"background-color: rgb(250, 170, 220)")
        self.btn_pow.setObjectName("btn_pow")
        self.btn_factorial = QtWidgets.QPushButton(self.centralwidget)
        self.btn_factorial.setGeometry(QtCore.QRect(310, 90, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_factorial.setFont(font)
        self.btn_factorial.setStyleSheet("color: rgb(30, 70, 30);\n"
"background-color: rgb(250, 170, 220)")
        self.btn_factorial.setObjectName("btn_factorial")
        self.btn_backet_close = QtWidgets.QPushButton(self.centralwidget)
        self.btn_backet_close.setGeometry(QtCore.QRect(310, 190, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_backet_close.setFont(font)
        self.btn_backet_close.setStyleSheet("color: rgb(30, 70, 30);\n"
"background-color: rgb(250, 170, 220)")
        self.btn_backet_close.setObjectName("btn_backet_close")
        self.btn_backet_open = QtWidgets.QPushButton(self.centralwidget)
        self.btn_backet_open.setGeometry(QtCore.QRect(310, 140, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_backet_open.setFont(font)
        self.btn_backet_open.setStyleSheet("color: rgb(30, 70, 30);\n"
"background-color: rgb(250, 170, 220)")
        self.btn_backet_open.setObjectName("btn_backet_open")
        self.btn_cls = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cls.setGeometry(QtCore.QRect(370, 90, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_cls.setFont(font)
        self.btn_cls.setStyleSheet("color: rgb(30, 70, 30);\n"
"background-color: rgb(250, 170, 220)")
        self.btn_cls.setObjectName("btn_cls")
        Calculate.setCentralWidget(self.centralwidget)

        self.retranslateUi(Calculate)
        QtCore.QMetaObject.connectSlotsByName(Calculate)

        self.add_functions()
    def retranslateUi(self, Calculate):
        _translate = QtCore.QCoreApplication.translate
        Calculate.setWindowTitle(_translate("Calculate", "Калькулятор"))
        self.label_result.setText(_translate("Calculate", "0"))
        self.label_input.setText(_translate("Calculate", "0"))
        self.label_equal.setText(_translate("Calculate", "="))
        self.btn_0.setText(_translate("Calculate", "0"))
        self.btn_8.setText(_translate("Calculate", "8"))
        self.btn_9.setText(_translate("Calculate", "9"))
        self.btn_7.setText(_translate("Calculate", "7"))
        self.btn_4.setText(_translate("Calculate", "4"))
        self.btn_5.setText(_translate("Calculate", "5"))
        self.btn_6.setText(_translate("Calculate", "6"))
        self.btn_1.setText(_translate("Calculate", "1"))
        self.btn_2.setText(_translate("Calculate", "2"))
        self.btn_3.setText(_translate("Calculate", "3"))
        self.btn_equal.setText(_translate("Calculate", "="))
        self.btn_division.setText(_translate("Calculate", "/"))
        self.btn_remainder_of_division.setText(_translate("Calculate", "%"))
        self.btn_minus.setText(_translate("Calculate", "-"))
        self.btn_plus.setText(_translate("Calculate", "+"))
        self.btn_multiply.setText(_translate("Calculate", "*"))
        self.btn_pow.setText(_translate("Calculate", "^"))
        self.btn_factorial.setText(_translate("Calculate", "!"))
        self.btn_backet_close.setText(_translate("Calculate", ")"))
        self.btn_backet_open.setText(_translate("Calculate", "("))
        self.btn_cls.setText(_translate("Calculate", "cls"))\
        

    def add_functions(self):
        self.btn_0.clicked.connect(lambda: self.write_symbol(self.btn_0.text()))
        self.btn_1.clicked.connect(lambda: self.write_symbol(self.btn_1.text()))
        self.btn_2.clicked.connect(lambda: self.write_symbol(self.btn_2.text()))
        self.btn_3.clicked.connect(lambda: self.write_symbol(self.btn_3.text()))
        self.btn_4.clicked.connect(lambda: self.write_symbol(self.btn_4.text()))
        self.btn_5.clicked.connect(lambda: self.write_symbol(self.btn_5.text()))
        self.btn_6.clicked.connect(lambda: self.write_symbol(self.btn_6.text()))
        self.btn_7.clicked.connect(lambda: self.write_symbol(self.btn_7.text()))
        self.btn_8.clicked.connect(lambda: self.write_symbol(self.btn_8.text()))
        self.btn_9.clicked.connect(lambda: self.write_symbol(self.btn_9.text()))
        self.btn_minus.clicked.connect(lambda: self.write_symbol(self.btn_minus.text()))
        self.btn_plus.clicked.connect(lambda: self.write_symbol(self.btn_plus.text()))
        self.btn_multiply.clicked.connect(lambda: self.write_symbol(self.btn_multiply.text()))
        self.btn_pow.clicked.connect(lambda: self.write_symbol(self.btn_pow.text()))
        self.btn_factorial.clicked.connect(lambda: self.write_symbol(self.btn_factorial.text()))
        self.btn_division.clicked.connect(lambda: self.write_symbol(self.btn_division.text()))
        self.btn_remainder_of_division.clicked.connect(lambda: self.write_symbol(self.btn_remainder_of_division.text()))
        self.btn_backet_close.clicked.connect(lambda: self.write_symbol(self.btn_backet_close.text()))
        self.btn_backet_open.clicked.connect(lambda: self.write_symbol(self.btn_backet_open.text()))

        self.btn_equal.clicked.connect(self.results)
        self.btn_cls.clicked.connect(self.cls)


    def cls(self):
        text = self.label_input.text()
        if len(text) == 1:
            self.label_input.setText('0')
        else:
            self.label_input.setText(text[:len(text)-1])

    def write_symbol(self, symbol : str):
        if self.label_input.text() == '0':
            self.label_input.setText(symbol)
        else:
            self.label_input.setText(self.label_input.text() + symbol)

    def results(self):
        res = self.ourEval.getAnswerToExpression(self.label_input.text())
        self.label_result.setText(str(res))

if __name__ == '__main__':
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Calculate = QtWidgets.QMainWindow()
    ui = Ui_Calculate()
    ui.setupUi(Calculate)
    Calculate.show()
    sys.exit(app.exec_())

